name: test.yml
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install

      - name: Run tests
        run: npm run test
        env:
          VITE_API_KEY: "test-weather-key"
          VITE_UNSPLASH_ACCESS_KEY: "test-unsplash-key"